### ISSUE TITLE
Bullet remain in the game field, killing every zombie it collide with

### ISSUE THREAD

**Issue by PaoloPenazzi** [PaoloPenazzi/pps-pvzlike#16]
Unfortunately this seem to be a bug that occur randomly.
At the moment I can't provide a series of steps to reproduce this bug.

**Comment by AngeloParrinello** [comment]
**Fixed**
_When_: the bug occurred when the troop entity, that generated the bullet, died when the bullet still flew in the field. 
In that way, the actor that created the bullet didn't receive the message of the bullet's death, and the actor (and also the sprite) was kept in the system, blocked there. 
_How_: the troop actor, when dying, sends an EntityDead message to the GameLoop with its Bullet references. 
Where: see commit [](https://github.com/PaoloPenazzi/pps-pvzlike/commit/ccdfb9414f89ad1d93983bb7fc40b27c1a0f7efe)
